steps:
  - id: 'branch name'
    name: 'alpine'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        echo "***********************"
        echo "Youssef"
        echo "***********************"

timeout:  3600s
#logsBucket : 'gs://.../cloud-build-logs'
#TODO: remove logging options when log output to bucket restored
options:
  logging: CLOUD_LOGGING_ONLY