project_id         = "sbx-mydataplatform"
region             = "europe-west1"
bucket_location    = "europe-west1"
bucket_storage_class = "STANDARD"
tf_state_bucket    = "sbx-mydataplatform-tfstate-bucket"
tf_state_prefix    = "tfstate/"
